### PR TITLE
Fix nodejs version issue

### PR DESCRIPTION
**Pull request by MiselAdemi**
Fix for nodejs version issue using yarn

### CODE REVIEW

**Review by azizali — APPROVED** [review]

**Comment by tmm1** [comment]
@azizali Any chance you can push out a v0.3.3-beta.1 with this fix?

**Comment by azizali** [comment]
Sure will do over the weekend

**Comment by tmm1** [comment]
@azizali Friendly ping re: new release

**Comment by tmm1** [comment]
Hi, really need a new release so all my `yarn` invocations don't keep failing as so:

```
error react-super-treeview@0.3.3: The engine "node" is incompatible with this module. Expected version "^6.7.0". Got "16.6.1"
error Found incompatible module.
```

**Pull request merged**
